### ISSUE TITLE
ERROR: MethodError: Cannot `convert` an object of type   ObservableTree{1} to an object of type   Dict

### ISSUE THREAD

**Issue by procuteboy** [Qiaoyi-Li/FiniteMPS.jl#5]
我在运行示例文件（[Hubbard_DMRG]）出现如下错误
ERROR: MethodError: Cannot `convert` an object of type   ObservableTree{1} to an object of type   Dict
看起来convert函数不能作用于Tree，不清楚什么原因？

**Comment by Qiaoyi-Li** [comment]
我在本地测试最新版本的该示例脚本是正常工作的。注意我在该次版本更新[v1.4.0](https://github.com/Qiaoyi-Li/FiniteMPS.jl/releases/tag/v1.4.0)中修改了相关函数的用法，你可以先检查下执行该脚本时环境的FiniteMPS版本号以及对比本地示例脚本与当前主分支示例脚本，看看用法是否一致，来尝试排查。

**Comment by procuteboy** [comment]
测试成功，主要时MPSKit与FiniteMPS有所冲突，rm 相关包，重新安装FiniteMPS 升级至1.4.2可以解决该问题。
